### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by Cushione** [Cushione/photora_frontend#19]
## Tasks

- [x] Set up react router
- [x] Add root layout
- [x] Add error page
- [x] Add routes
